/* Property-based tests for trade_calc — INVARIANTS only.
 *
 * Companion to trade_calc.test.ts (21 literal/hand-derived cases).
 * These assert PROPERTIES that must hold over hundreds of random
 * inputs generated by fast-check. They never re-use the
 * implementation's own functions to compute an "expected" value —
 * invariants are independent of any specific numeric output, so the
 * tests cannot be biased toward the implementation by construction.
 */

import fc from "fast-check";
import { describe, expect, it } from "vitest";
import {
  compute_buy_shortfall,
  compute_cash_after,
  compute_quantity_from_pct,
  compute_quantity_from_shares,
  compute_realized_pnl,
  compute_shares_after,
  compute_short_quantity,
} from "./trade_calc";

// Strategies — realistic envelopes (a fund-XI portfolio is at most a
// few hundred €M; a share count is small fractional; price 0.01..300).
const f_amount = fc.double({ min: 0, max: 100_000, noNaN: true, noDefaultInfinity: true });
const f_price = fc.double({ min: 0.01, max: 300, noNaN: true, noDefaultInfinity: true });
const f_shares = fc.double({ min: 0.1, max: 100, noNaN: true, noDefaultInfinity: true });
const f_pct = fc.double({ min: 0, max: 100, noNaN: true, noDefaultInfinity: true });

describe("trade_calc — property-based invariants", () => {
  it("compute_quantity_from_pct: amount is exactly round(portfolio_value * pct / 100), always integer M€", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_price, (portfolio_value, pct, price) => {
        const { amount } = compute_quantity_from_pct(portfolio_value, pct, price);
        // amount is the integer M€ rounding of portfolio_value * pct / 100,
        // independent of price. Catches a price-mistakenly-folded-into-amount bug.
        expect(amount).toBe(Math.round((portfolio_value * pct) / 100));
      }),
    );
  });

  it("compute_quantity_from_pct: shares are always a 0.1-multiple (the SHARES_QUANTUM invariant)", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_price, (portfolio_value, pct, price) => {
        const { shares } = compute_quantity_from_pct(portfolio_value, pct, price);
        // shares * 10 must be an exact integer (within float epsilon).
        // Catches a rounding regression that lets a 0.07-share order slip through.
        const x10 = shares * 10;
        expect(Math.abs(x10 - Math.round(x10))).toBeLessThan(1e-9);
      }),
    );
  });

  it("compute_quantity_from_pct: a BUY never over-commits cash (floor protects against over-spend)", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_price, (portfolio_value, pct, price) => {
        const { amount, shares } = compute_quantity_from_pct(portfolio_value, pct, price);
        // shares * price <= amount (within €1M because amount itself is rounded
        // to nearest M€ and shares are floored to 0.1, so cost <= amount + 0.5).
        if (price > 0) expect(shares * price).toBeLessThanOrEqual(amount + 0.5 + 1e-9);
      }),
    );
  });

  it("compute_quantity_from_shares: amount == round(shares * price) — no other variable matters", () => {
    fc.assert(
      fc.property(f_shares, f_price, (shares, price) => {
        expect(compute_quantity_from_shares(shares, price).amount).toBe(Math.round(shares * price));
      }),
    );
  });

  it("compute_shares_after: a buy then a sell of the SAME quantity returns to the prior holding", () => {
    // Round-trip invariant in pure arithmetic — catches a sign/direction bug.
    fc.assert(
      fc.property(f_shares, f_shares, (held, trade) => {
        const after_buy = compute_shares_after("buy", held, trade);
        const after_sell = compute_shares_after("sell", after_buy, trade);
        // float epsilon allowed — pure subtraction can drift on subnormal-ish values.
        expect(Math.abs(after_sell - held)).toBeLessThan(1e-9);
      }),
    );
  });

  it("compute_cash_after: a buy followed by a sell of the SAME amount returns cash to its starting value", () => {
    fc.assert(
      fc.property(f_amount, f_amount, (cash, amount) => {
        const after_buy = compute_cash_after("buy", cash, amount);
        const after_sell = compute_cash_after("sell", after_buy, amount);
        expect(Math.abs(after_sell - cash)).toBeLessThan(1e-9);
      }),
    );
  });

  it("compute_realized_pnl: always exactly 0 on a buy, regardless of any other input", () => {
    fc.assert(
      fc.property(f_shares, f_price, f_price, f_shares, (trade, cur, avg, held) => {
        expect(compute_realized_pnl("buy", trade, cur, avg, held)).toBe(0);
      }),
    );
  });

  it("compute_realized_pnl on a sell: bounded by held shares — selling beyond doesn't grow the realized leg", () => {
    fc.assert(
      fc.property(f_shares, f_price, f_price, f_shares, (trade, cur, avg, held) => {
        const pnl = compute_realized_pnl("sell", trade, cur, avg, held);
        // |pnl| <= |cur - avg| * held (the closing portion is capped at held).
        expect(Math.abs(pnl)).toBeLessThanOrEqual(Math.abs(cur - avg) * Math.max(held, 0) + 1e-6);
      }),
    );
  });

  it("compute_short_quantity: never negative; > 0 only on a sell that exceeds held", () => {
    fc.assert(
      fc.property(fc.constantFrom("buy", "sell" as const), f_shares, f_shares, (kind, req, held) => {
        const sq = compute_short_quantity(kind as "buy" | "sell", req, held);
        expect(sq).toBeGreaterThanOrEqual(0);
        if (kind === "buy" || req <= held) expect(sq).toBe(0);
      }),
    );
  });

  it("compute_buy_shortfall: insufficient iff amount > cash; sells never report a shortfall", () => {
    fc.assert(
      fc.property(fc.constantFrom("buy", "sell" as const), f_amount, f_amount, (kind, amount, cash) => {
        const { insufficient, shortfall } = compute_buy_shortfall(kind as "buy" | "sell", amount, cash);
        if (kind === "sell") {
          expect(insufficient).toBe(false);
          expect(shortfall).toBe(0);
        } else {
          expect(insufficient).toBe(amount > cash);
          if (insufficient) expect(shortfall).toBeCloseTo(amount - cash, 9);
        }
      }),
    );
  });
});
