"""Property-based tests for the canonical pricing kernel — INVARIANTS only.

The unit tests in ``test_pricing_kernel.py`` assert literal values
hand-computed from the spec. These tests assert PROPERTIES that must
hold over RANDOM inputs generated by Hypothesis. They never use the
implementation's own functions/constants to compute an "expected"
value — invariants are independent of any specific numeric output, so
the tests cannot be biased toward the implementation by construction.

Together (literal cases + properties), they form the strongest
correctness guarantee we can give without real data: deterministic
spec-anchored examples + hundreds of random inputs against
spec-anchored invariants.
"""

import math

from hypothesis import given
from hypothesis import strategies as st

from src.valuation.pricing import (
    PriceSnapshot,
    apply_tournament_event,
    live_delta,
    multiplier,
    price,
    rating_level,
    settle,
    volatility,
)

# Strategies — bounded to realistic ranges so the tests target the
# operating envelope (a fund-XI base is 1..300 M€; a rating is 0..10;
# pressure is 0..2 even after Sportmonks bounds; tournament_delta of
# ±2.0 is far beyond any realistic accumulation).
_base = st.floats(min_value=1.0, max_value=300.0, allow_nan=False, allow_infinity=False)
_rating = st.floats(min_value=0.0, max_value=10.0, allow_nan=False, allow_infinity=False)
_pressure = st.one_of(st.none(), st.floats(min_value=0.0, max_value=2.0, allow_nan=False, allow_infinity=False))
_td = st.floats(min_value=-2.0, max_value=2.0, allow_nan=False, allow_infinity=False)


def _snap(rating: float | None, *, is_live: bool = True, pressure: float | None = None) -> PriceSnapshot:
    return PriceSnapshot(rating=rating, is_live=is_live, pressure_factor=pressure)


# 1. Strict positivity — spec invariant, no input can drive price ≤ 0.
@given(base=_base, td=_td, r=_rating, p=_pressure)
def test_price_is_always_strictly_positive(base: float, td: float, r: float, p: float | None) -> None:
    assert price(base, td, _snap(r, pressure=p)).price > 0.0


# 2. Monotonic in rating — same inputs, higher rating ⇒ price never falls.
# This is THE behavioural property: a player playing better is never
# worth less. Mutation in the rating-level sign would surface here.
@given(base=_base, td=_td, r1=_rating, r2=_rating, p=_pressure)
def test_price_is_monotonic_in_rating(base: float, td: float, r1: float, r2: float, p: float | None) -> None:
    lo, hi = (r1, r2) if r1 <= r2 else (r2, r1)
    assert price(base, td, _snap(hi, pressure=p)).price >= price(base, td, _snap(lo, pressure=p)).price


# 3. Rating baseline 6.0 ⇒ zero live contribution — spec §4.1 anchor.
# Independent of base/pressure/td, except for rounding the price.
@given(base=_base, p=_pressure)
def test_neutral_rating_contributes_nothing(base: float, p: float | None) -> None:
    assert live_delta(_snap(6.0, pressure=p), base) == 0.0


# 4. Settlement is a pure sum — no hidden state, no rounding side-effect.
@given(td=_td, ld=st.floats(min_value=-1.0, max_value=1.0, allow_nan=False))
def test_settle_is_pure_addition(td: float, ld: float) -> None:
    assert settle(td, ld) == td + ld


# 5. Tournament events commute — applying A then B equals B then A
# (float associativity tolerated; the property is mathematical sum).
@given(td=_td, a=_td, b=_td)
def test_tournament_events_commute(td: float, a: float, b: float) -> None:
    left = apply_tournament_event(apply_tournament_event(td, a), b)
    right = apply_tournament_event(apply_tournament_event(td, b), a)
    assert math.isclose(left, right, rel_tol=1e-9, abs_tol=1e-12)


# 6. Off-match flat — when the match is not live, the price reflects
# ONLY the tournament balance (LiveDelta is structurally 0), so it
# equals base * (1 + td) within the kernel's 2-decimal rounding.
@given(base=_base, td=_td, r=_rating, p=_pressure)
def test_off_match_price_is_flat(base: float, td: float, r: float, p: float | None) -> None:
    off = price(base, td, _snap(r, is_live=False, pressure=p))
    assert off.live_delta == 0.0
    # 2-decimal rounding ⇒ at most 0.005 absolute error.
    assert abs(off.price - max(0.05, 1.0 + td) * base) <= 0.005 + 1e-9


# 7. Live delta is bounded — never explodes, never NaN, never infinite.
@given(base=_base, r=_rating, p=_pressure)
def test_live_delta_is_finite_and_bounded(base: float, r: float, p: float | None) -> None:
    ld = live_delta(_snap(r, pressure=p), base)
    assert math.isfinite(ld)
    # Spec ceil 0.40, floor -0.30, scaled by volatility (≤ vol(1) ≈ 5.74)
    # and pressure (≤ 1.3). 0.40 * 6 * 1.3 ≈ 3.12 is a very loose upper
    # envelope; if ld ever exceeds this, something is wrong structurally.
    assert abs(ld) < 3.5


# 8. Pressure modulator clamp — vary ONLY pressure on otherwise-identical
# inputs and assert effective factor stays within [0.7, 1.3] of identity.
@given(base=_base, r=_rating, p=_pressure)
def test_pressure_only_scales_within_clamp(base: float, r: float, p: float | None) -> None:
    no_p = live_delta(_snap(r), base)
    with_p = live_delta(_snap(r, pressure=p), base)
    if no_p == 0.0:
        assert with_p == 0.0
        return
    ratio = with_p / no_p
    # Clamp [0.7, 1.3] per spec L3 (small float epsilon).
    assert 0.7 - 1e-9 <= ratio <= 1.3 + 1e-9


# 9. Rating level scales linearly with the rating above baseline.
# Independent property: doubling the (rating - 6) doubles the level.
# Catches a non-linear bug (e.g., squared, sigmoid) anywhere.
# Float-aware comparison: arithmetic is associatively imprecise.
@given(d=st.floats(min_value=-3.0, max_value=3.0, allow_nan=False))
def test_rating_level_is_linear_in_rating_offset(d: float) -> None:
    a = rating_level(6.0 + d)
    b = rating_level(6.0 + 2.0 * d)
    assert math.isclose(b, 2.0 * a, rel_tol=1e-9, abs_tol=1e-12)


# 10. Multiplier respects its floor for any inputs.
@given(td=_td, ld=st.floats(min_value=-2.0, max_value=2.0, allow_nan=False))
def test_multiplier_respects_its_floor(td: float, ld: float) -> None:
    m = multiplier(td, ld)
    assert m > 0.0
    # If the "natural" value 1+td+ld is well above the floor, it must be
    # returned as-is (the floor doesn't clip unnecessarily).
    natural = 1.0 + td + ld
    if natural >= 0.10:  # safely above the 0.05 floor
        assert m == natural


# 11. Volatility is monotonically decreasing in base (small caps move
# harder than blue chips, spec §4.2) and stays strictly positive.
@given(b1=_base, b2=_base)
def test_volatility_is_monotonically_decreasing_in_base(b1: float, b2: float) -> None:
    v1 = volatility(b1)
    v2 = volatility(b2)
    assert v1 > 0.0 and v2 > 0.0
    if b1 < b2:
        assert v1 >= v2
    elif b1 > b2:
        assert v1 <= v2
