/* Property-based tests for trade_calc — INVARIANTS only.
 *
 * Companion to trade_calc.test.ts (hand-derived cases). These assert PROPERTIES
 * that must hold over hundreds of random inputs generated by fast-check. They
 * never re-use the implementation's own functions to compute an "expected"
 * value — invariants are independent of any specific numeric output, so the
 * tests cannot be biased toward the implementation by construction.
 *
 * Model reminder: a position is an ownership_fraction of the player's whole
 * value (|fraction| ≤ 1); N = shares_per_player is a display denomination; the
 * trade cost = fraction × total_value.
 */

import fc from "fast-check";
import { describe, expect, it } from "vitest";
import {
  buy_quantity_from_cash_pct,
  cap_trade_fraction,
  compute_buy_shortfall,
  compute_cash_after,
  compute_quantity_from_shares,
  compute_realized_pnl,
  compute_shares_after,
  fraction_from_display_shares,
  sell_quantity_from_position_pct,
  to_display_shares,
  trade_headroom_fraction,
} from "./trade_calc";

// Size by % the way the app does, dispatching on side: buy = % of cash,
// sell = % of the held position.
const quantity_from_pct = (
  cash: number,
  pct: number,
  value: number,
  n: number,
  kind: "buy" | "sell",
  held: number,
) =>
  kind === "buy"
    ? buy_quantity_from_cash_pct(cash, pct, value, n, held)
    : sell_quantity_from_position_pct(held, pct, value, n);

const f_amount = fc.double({ min: 0, max: 100_000, noNaN: true, noDefaultInfinity: true });
const f_value = fc.double({ min: 0.01, max: 300, noNaN: true, noDefaultInfinity: true });
const f_frac = fc.double({ min: 0, max: 1, noNaN: true, noDefaultInfinity: true });
const f_pct = fc.double({ min: 0, max: 100, noNaN: true, noDefaultInfinity: true });
const f_n = fc.constantFrom(10, 100, 1000, 100_000, 1_000_000);
const f_kind = fc.constantFrom("buy", "sell") as fc.Arbitrary<"buy" | "sell">;
// A held fraction snapped to the share grid for N (positions are always built
// from quantised trades, so the cap can never produce an off-grid result).
const held_on_grid = (raw: number, n: number) => Math.max(-1, Math.min(1, Math.round(raw * n) / n));

const is_quantum_multiple = (shares: number, n: number) => Math.abs(shares * n - Math.round(shares * n)) < 1e-6;

describe("trade_calc — property-based invariants", () => {
  it("from_pct: amount is the resulting fraction's actual cost, rounded to the cent", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_value, f_n, f_kind, f_frac, (pv, pct, value, n, kind, raw) => {
        const held = held_on_grid(raw < 0.5 ? raw * 2 - 1 : raw, n); // span shorts and longs
        const { amount, shares } = quantity_from_pct(pv, pct, value, n, kind, held);
        expect(amount).toBe(Math.round(shares * value * 100) / 100);
      }),
    );
  });

  it("from_pct: shares are always a 1/N multiple (the quantum invariant)", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_value, f_n, f_kind, f_frac, (pv, pct, value, n, kind, raw) => {
        const held = held_on_grid(raw * 2 - 1, n);
        const { shares } = quantity_from_pct(pv, pct, value, n, kind, held);
        expect(is_quantum_multiple(shares, n)).toBe(true);
      }),
    );
  });

  it("from_pct: the resulting position never exceeds ±100% of the player", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_value, f_n, f_kind, f_frac, (pv, pct, value, n, kind, raw) => {
        const held = held_on_grid(raw * 2 - 1, n);
        const { shares } = quantity_from_pct(pv, pct, value, n, kind, held);
        expect(shares).toBeGreaterThanOrEqual(0);
        const after = kind === "buy" ? held + shares : held - shares;
        expect(Math.abs(after)).toBeLessThanOrEqual(1 + 1e-9);
      }),
    );
  });

  it("from_pct: a BUY never over-commits the budget (cost ≤ budget)", () => {
    fc.assert(
      fc.property(f_amount, f_pct, f_value, f_n, f_frac, (pv, pct, value, n, raw) => {
        const held = held_on_grid(raw, n); // long side, so the budget — not just the cap — binds
        const { shares } = quantity_from_pct(pv, pct, value, n, "buy", held);
        expect(shares * value).toBeLessThanOrEqual((pv * pct) / 100 + 1e-9);
      }),
    );
  });

  it("from_shares: amount == round-to-cent(shares × value); position within cap", () => {
    fc.assert(
      fc.property(fc.double({ min: 0, max: 5_000_000, noNaN: true, noDefaultInfinity: true }), f_value, f_n, f_kind, f_frac, (ds, value, n, kind, raw) => {
        const held = held_on_grid(raw * 2 - 1, n);
        const { amount, shares } = compute_quantity_from_shares(ds, value, n, kind, held);
        expect(amount).toBe(Math.round(shares * value * 100) / 100);
        const after = kind === "buy" ? held + shares : held - shares;
        expect(Math.abs(after)).toBeLessThanOrEqual(1 + 1e-9);
      }),
    );
  });

  it("cap_trade_fraction: result is within [0, headroom] and never exceeds the request", () => {
    fc.assert(
      fc.property(f_kind, f_frac, fc.double({ min: 0, max: 3, noNaN: true, noDefaultInfinity: true }), (kind, raw, req) => {
        const held = Math.max(-1, Math.min(1, raw * 2 - 1));
        const capped = cap_trade_fraction(kind, held, req);
        expect(capped).toBeGreaterThanOrEqual(0);
        expect(capped).toBeLessThanOrEqual(req + 1e-12);
        expect(capped).toBeLessThanOrEqual(trade_headroom_fraction(kind, held) + 1e-12);
      }),
    );
  });

  it("display round-trip: fraction → shares → fraction is identity", () => {
    fc.assert(
      fc.property(f_frac, f_n, (frac, n) => {
        expect(fraction_from_display_shares(to_display_shares(frac, n), n)).toBeCloseTo(frac, 9);
      }),
    );
  });

  it("compute_shares_after: a buy then a sell of the SAME quantity returns to the prior holding", () => {
    fc.assert(
      fc.property(f_frac, f_frac, (held, trade) => {
        const after_buy = compute_shares_after("buy", held, trade);
        const after_sell = compute_shares_after("sell", after_buy, trade);
        expect(Math.abs(after_sell - held)).toBeLessThan(1e-9);
      }),
    );
  });

  it("compute_cash_after: a buy followed by a sell of the SAME amount returns cash to its start", () => {
    fc.assert(
      fc.property(f_amount, f_amount, (cash, amount) => {
        const after_buy = compute_cash_after("buy", cash, amount);
        const after_sell = compute_cash_after("sell", after_buy, amount);
        expect(Math.abs(after_sell - cash)).toBeLessThan(1e-9);
      }),
    );
  });

  it("compute_realized_pnl: always exactly 0 on a buy", () => {
    fc.assert(
      fc.property(f_frac, f_value, f_value, f_frac, (trade, cur, avg, held) => {
        expect(compute_realized_pnl("buy", trade, cur, avg, held)).toBe(0);
      }),
    );
  });

  it("compute_realized_pnl on a sell: bounded by held shares", () => {
    fc.assert(
      fc.property(f_frac, f_value, f_value, f_frac, (trade, cur, avg, held) => {
        const pnl = compute_realized_pnl("sell", trade, cur, avg, held);
        expect(Math.abs(pnl)).toBeLessThanOrEqual(Math.abs(cur - avg) * Math.max(held, 0) + 1e-6);
      }),
    );
  });


  it("compute_buy_shortfall: insufficient iff amount > cash; sells never report a shortfall", () => {
    fc.assert(
      fc.property(f_kind, f_amount, f_amount, (kind, amount, cash) => {
        const { insufficient, shortfall } = compute_buy_shortfall(kind, amount, cash);
        if (kind === "sell") {
          expect(insufficient).toBe(false);
          expect(shortfall).toBe(0);
        } else {
          expect(insufficient).toBe(amount > cash);
          if (insufficient) expect(shortfall).toBeCloseTo(amount - cash, 9);
        }
      }),
    );
  });
});
